### ISSUE TITLE
Libigl permissions issue (same as the reconstruction assignment)

### ISSUE THREAD

**Issue by GavinBarill** [alecjacobson/geometry-processing-smoothing#13]
I'm getting the same issue with the recursive cloning into the shared respository that we had with the Poisson Surface Reconstruction assignment.

When trying to clone, it says:
"Cloning into '/Users/gavinbarill/Documents/School/GradSchool/GeometryProcessing/geometry-processing-smoothing/shared/libigl'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists."

**Comment by alecjacobson** [comment]
I haven't updated this one yet. I've been doing it as they get assigned.
