### ISSUE TITLE
Small sign issue in README

### ISSUE THREAD

**Issue by GavinBarill** [alecjacobson/geometry-processing-smoothing#15]
<img width="369" alt="screen shot 2018-02-11 at 2 43 35 pm" src="https://user-images.githubusercontent.com/9832231/36077529-feab31ce-0f39-11e8-8ef0-1ecc38679478.png">
The case where i = j, should be multiplied by -1. It's in the .h file for the cotmatix function, so it's easy enough not to follow the mistake through.

**Comment by alecjacobson** [comment]
Can you submit a pull request to the main branch?
