### ISSUE TITLE
Equations in flow based formulation

### ISSUE THREAD

**Issue by Ming-Yeung-Alfred-Meng** [alecjacobson/geometry-processing-smoothing#54]
![image](https://user-images.githubusercontent.com/81248498/194452340-4d494ca9-0f8e-4a42-b540-ede62fd7f6d6.png)

Could you please clarify how you derived the equation of the derivative from the one above it?

**Comment by alecjacobson** [comment]
There's an extra |B(x)| in the top equations that's now been corrected. To get to the next we using that (u^(t+dt) - u^t)/dt → ∂u/∂t as dt→0
