### ISSUE TITLE
Possible missing term in energy based formulation.

### ISSUE THREAD

**Issue by Ming-Yeung-Alfred-Meng** [alecjacobson/geometry-processing-smoothing#56]
![image](https://user-images.githubusercontent.com/81248498/194455494-1354f127-b5f1-4d94-8d83-a599ac733def.png)

I guess the second equation is missing one half of the derivative of epsilon squared v squared from the equation above. But I guess it don't matter too much since we are evaluating epsilon = 0 next.

**Comment by alecjacobson** [comment]
I think the issue is that there's a ‖∇w‖² instead of ‖∇v‖². I'll fix that .
